name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
 
jobs:
 Explore-GitHub-Actions:
   runs-on: ubuntu-latest

   strategy:
     matrix:
       node-version: [20.x]

   steps:
      - run: echo "checking out code repository"
      - name: Check out repository code
        uses: actions/checkout@v4
 
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
         node-version: ${{ matrix.node-version }}
 
      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install

      - name: Run Playwright tests
        run: npx playwright test
 
      - name: Upload Playwright report artifact
        uses: actions/upload-artifact@v2
        with:
         name: playwright-report
         path: playwright-report